name: Push

on: 
  push:
    branches:
      - '**'
      
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
      
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore