name: Push

on: 
  push:
    branches:
      - '**'
      
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
      
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Restore
        run: dotnet restore src
        
      - name: Build
        run: dotnet build src --configuration Release --no-restore
